<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Kid extends \App\Entity\Kid implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'birthDate' => [parent::class, 'birthDate', null],
        "\0".'*'."\0".'email' => [parent::class, 'email', null],
        "\0".'*'."\0".'firstName' => [parent::class, 'firstName', null],
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".'*'."\0".'password' => [parent::class, 'password', null],
        "\0".'*'."\0".'registrationDate' => [parent::class, 'registrationDate', null],
        "\0".'*'."\0".'secondName' => [parent::class, 'secondName', null],
        "\0".parent::class."\0".'challenges' => [parent::class, 'challenges', null],
        "\0".parent::class."\0".'friends' => [parent::class, 'friends', null],
        "\0".parent::class."\0".'interests' => [parent::class, 'interests', null],
        "\0".parent::class."\0".'level' => [parent::class, 'level', null],
        "\0".parent::class."\0".'points' => [parent::class, 'points', null],
        "\0".parent::class."\0".'responses' => [parent::class, 'responses', null],
        "\0".'App\\Entity\\User'."\0".'posts' => ['App\\Entity\\User', 'posts', null],
        'birthDate' => [parent::class, 'birthDate', null],
        'challenges' => [parent::class, 'challenges', null],
        'email' => [parent::class, 'email', null],
        'firstName' => [parent::class, 'firstName', null],
        'friends' => [parent::class, 'friends', null],
        'id' => [parent::class, 'id', null],
        'interests' => [parent::class, 'interests', null],
        'level' => [parent::class, 'level', null],
        'password' => [parent::class, 'password', null],
        'points' => [parent::class, 'points', null],
        'posts' => ['App\\Entity\\User', 'posts', null],
        'registrationDate' => [parent::class, 'registrationDate', null],
        'responses' => [parent::class, 'responses', null],
        'secondName' => [parent::class, 'secondName', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
