<?php

namespace ContainerKn2TlEr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MIzpu1lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MIzpu1l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MIzpu1l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kidParent' => ['privates', '.errored..service_locator.MIzpu1l.App\\Entity\\KidParent', NULL, 'Cannot autowire service ".service_locator.MIzpu1l": it needs an instance of "App\\Entity\\KidParent" but this type has been excluded in "config/services.yaml".'],
        ], [
            'kidParent' => 'App\\Entity\\KidParent',
        ]);
    }
}
