<?php

namespace ContainerKn2TlEr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ONL1CxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oN_l1Cx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oN_l1Cx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'option' => ['privates', '.errored..service_locator.oN_l1Cx.App\\Entity\\Option', NULL, 'Cannot autowire service ".service_locator.oN_l1Cx": it needs an instance of "App\\Entity\\Option" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'option' => 'App\\Entity\\Option',
        ]);
    }
}
