<?php

namespace ContainerKn2TlEr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GwRhffbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GwRhffb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GwRhffb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chapter' => ['privates', '.errored..service_locator.GwRhffb.App\\Entity\\Chapter', NULL, 'Cannot autowire service ".service_locator.GwRhffb": it needs an instance of "App\\Entity\\Chapter" but this type has been excluded in "config/services.yaml".'],
        ], [
            'chapter' => 'App\\Entity\\Chapter',
        ]);
    }
}
