<?php

namespace ContainerKn2TlEr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKidParent2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.l5UavKc.App\Entity\KidParent' shared service.
     *
     * @return \App\Entity\KidParent
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.l5UavKc": it needs an instance of "App\\Entity\\KidParent" but this type has been excluded in "config/services.yaml".');
    }
}
