<?php

namespace ContainerDvkLEFx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A9P__S4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a9P..S4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a9P..S4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'optionRepository' => ['privates', 'App\\Repository\\OptionRepository', 'getOptionRepositoryService', true],
            'question' => ['privates', '.errored..service_locator.a9P..S4.App\\Entity\\Question', NULL, 'Cannot autowire service ".service_locator.a9P..S4": it needs an instance of "App\\Entity\\Question" but this type has been excluded in "config/services.yaml".'],
        ], [
            'optionRepository' => 'App\\Repository\\OptionRepository',
            'question' => 'App\\Entity\\Question',
        ]);
    }
}
