<?php

namespace ContainerDvkLEFx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W9yDc2xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w9yDc2x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w9yDc2x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'optionRepository' => ['privates', 'App\\Repository\\OptionRepository', 'getOptionRepositoryService', true],
        ], [
            'entityManager' => '?',
            'optionRepository' => 'App\\Repository\\OptionRepository',
        ]);
    }
}
