<?php

namespace ContainerDvkLEFx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKidService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xcCEpiT.App\Entity\Kid' shared service.
     *
     * @return \App\Entity\Kid
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.xcCEpiT": it needs an instance of "App\\Entity\\Kid" but this type has been excluded in "config/services.yaml".');
    }
}
