<?php

namespace ContainerTXRgmot;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ot8YwmfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ot8Ywmf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ot8Ywmf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lesson' => ['privates', '.errored..service_locator.ot8Ywmf.App\\Entity\\Lesson', NULL, 'Cannot autowire service ".service_locator.ot8Ywmf": it needs an instance of "App\\Entity\\Lesson" but this type has been excluded in "config/services.yaml".'],
            'quizRepository' => ['privates', 'App\\Repository\\QuizRepository', 'getQuizRepositoryService', true],
        ], [
            'lesson' => 'App\\Entity\\Lesson',
            'quizRepository' => 'App\\Repository\\QuizRepository',
        ]);
    }
}
