<?php

namespace ContainerTXRgmot;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BUbOYheService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BUbOYhe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BUbOYhe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lesson' => ['privates', '.errored..service_locator.BUbOYhe.App\\Entity\\Lesson', NULL, 'Cannot autowire service ".service_locator.BUbOYhe": it needs an instance of "App\\Entity\\Lesson" but this type has been excluded in "config/services.yaml".'],
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.BUbOYhe.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.BUbOYhe": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'lesson' => 'App\\Entity\\Lesson',
            'postRepository' => 'App\\Repository\\PostRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
