<?php

namespace ContainerTXRgmot;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XcCEpiTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xcCEpiT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xcCEpiT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'kid' => ['privates', '.errored..service_locator.xcCEpiT.App\\Entity\\Kid', NULL, 'Cannot autowire service ".service_locator.xcCEpiT": it needs an instance of "App\\Entity\\Kid" but this type has been excluded in "config/services.yaml".'],
            'quiz' => ['privates', '.errored..service_locator.xcCEpiT.App\\Entity\\Quiz', NULL, 'Cannot autowire service ".service_locator.xcCEpiT": it needs an instance of "App\\Entity\\Quiz" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'kid' => 'App\\Entity\\Kid',
            'quiz' => 'App\\Entity\\Quiz',
        ]);
    }
}
