<?php

namespace ContainerTXRgmot;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuestionServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\QuestionService' shared autowired service.
     *
     * @return \App\Service\QuestionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'QuestionService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'OptionService.php';

        return $container->privates['App\\Service\\QuestionService'] = new \App\Service\QuestionService(($container->privates['App\\Service\\OptionService'] ??= new \App\Service\OptionService()));
    }
}
