<?php

namespace ContainerHx2x8jq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6lWLSx2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6lWLSx2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6lWLSx2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'kidRepository' => ['privates', 'App\\Repository\\KidRepository', 'getKidRepositoryService', true],
        ], [
            'entityManager' => '?',
            'kidRepository' => 'App\\Repository\\KidRepository',
        ]);
    }
}
