<?php

namespace ContainerT58A8eJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QvnF8MrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qvnF8Mr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qvnF8Mr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coach' => ['privates', '.errored..service_locator.qvnF8Mr.App\\Entity\\Coach', NULL, 'Cannot autowire service ".service_locator.qvnF8Mr": it needs an instance of "App\\Entity\\Coach" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'coach' => 'App\\Entity\\Coach',
            'entityManager' => '?',
        ]);
    }
}
