<?php

namespace ContainerT58A8eJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KWbHO7FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KWbHO7F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KWbHO7F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'kid' => ['privates', '.errored..service_locator.KWbHO7F.App\\Entity\\Kid', NULL, 'Cannot autowire service ".service_locator.KWbHO7F": it needs an instance of "App\\Entity\\Kid" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'kid' => 'App\\Entity\\Kid',
        ]);
    }
}
