<?php

namespace ContainerT58A8eJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OOab1TuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oOab1Tu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oOab1Tu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kid' => ['privates', '.errored..service_locator.oOab1Tu.App\\Entity\\Kid', NULL, 'Cannot autowire service ".service_locator.oOab1Tu": it needs an instance of "App\\Entity\\Kid" but this type has been excluded in "config/services.yaml".'],
        ], [
            'kid' => 'App\\Entity\\Kid',
        ]);
    }
}
