<?php

namespace ContainerT58A8eJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChapterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GwRhffb.App\Entity\Chapter' shared service.
     *
     * @return \App\Entity\Chapter
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.GwRhffb": it needs an instance of "App\\Entity\\Chapter" but this type has been excluded in "config/services.yaml".');
    }
}
