<?php

namespace ContainerT58A8eJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKidResponseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Ul3VPgf.App\Entity\KidResponse' shared service.
     *
     * @return \App\Entity\KidResponse
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Ul3VPgf": it needs an instance of "App\\Entity\\KidResponse" but this type has been excluded in "config/services.yaml".');
    }
}
