<?php

namespace ContainerT58A8eJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOption2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oN_l1Cx.App\Entity\Option' shared service.
     *
     * @return \App\Entity\Option
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.oN_l1Cx": it needs an instance of "App\\Entity\\Option" but this type has been excluded in "config/services.yaml".');
    }
}
