<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMAjJsGW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMAjJsGW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMAjJsGW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMAjJsGW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMAjJsGW\App_KernelDevDebugContainer([
    'container.build_hash' => 'MAjJsGW',
    'container.build_id' => '8d489517',
    'container.build_time' => 1721308573,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMAjJsGW');
