<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT58A8eJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT58A8eJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT58A8eJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT58A8eJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT58A8eJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'T58A8eJ',
    'container.build_id' => '4f57e7ff',
    'container.build_time' => 1721216801,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT58A8eJ');
