<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC2QaR9r\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC2QaR9r/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC2QaR9r.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC2QaR9r\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC2QaR9r\App_KernelDevDebugContainer([
    'container.build_hash' => 'C2QaR9r',
    'container.build_id' => 'f7d2b136',
    'container.build_time' => 1721557059,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC2QaR9r');
